//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_INVOICE
    {
        public int DID { get; set; }
        public Nullable<int> ID { get; set; }
        public string IT_CODE { get; set; }
        public Nullable<decimal> IT_QTY { get; set; }
        public Nullable<decimal> IT_RATE { get; set; }
        public Nullable<decimal> IT_AMT { get; set; }
    
        public virtual HD_INVOICE HD_INVOICE { get; set; }
    }
}
