//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DT_LEAVE
    {
        public int ID { get; set; }
        public string LV_DOC_NO { get; set; }
        public Nullable<System.DateTime> LV_DOC_DATE { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> TT_ID { get; set; }
        public Nullable<System.DateTime> LV_DT_FROM { get; set; }
        public Nullable<System.DateTime> LV_DT_TO { get; set; }
        public string LV_EMAIL { get; set; }
    
        public virtual TTMAST TTMAST { get; set; }
    }
}
