//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Doc_History
    {
        public int id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> doc_id { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] dof_file { get; set; }
        public string doc_no { get; set; }
        public Nullable<System.DateTime> doc_issue_date { get; set; }
        public Nullable<System.DateTime> doc_expiry_date { get; set; }
    
        public virtual TTMAST TTMAST { get; set; }
        public virtual ANG_EMPLOYEE ANG_EMPLOYEE { get; set; }
    }
}
