//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPSAL
    {
        public int SL_ID { get; set; }
        public Nullable<int> EM_ID { get; set; }
        public Nullable<int> TT_ID { get; set; }
        public Nullable<decimal> SL_AMT { get; set; }
        public string SL_TYPE { get; set; }
        public string EM_CODE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual TTMAST TTMAST { get; set; }
    }
}
