//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_INVOICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HD_INVOICE()
        {
            this.DT_INVOICE = new HashSet<DT_INVOICE>();
        }
    
        public int ID { get; set; }
        public string IN_DOCNO { get; set; }
        public Nullable<System.DateTime> IN_DATE { get; set; }
        public string IN_DESCRIPTION { get; set; }
        public string IN_CUSTOMER { get; set; }
        public Nullable<decimal> IN_TOTAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DT_INVOICE> DT_INVOICE { get; set; }
    }
}
