//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long Item_Id { get; set; }
        public string Item_Code { get; set; }
        public string Item_Desc { get; set; }
        public Nullable<decimal> Item_Price { get; set; }
        public string Item_Category { get; set; }
        public Nullable<decimal> Item_Qty { get; set; }
        public Nullable<System.DateTime> Item_Date { get; set; }
        public Nullable<System.DateTime> Item_Expiry { get; set; }
        public Nullable<bool> Item_Inactive { get; set; }
        public string Item_Image { get; set; }
        public Nullable<int> Cat_Id { get; set; }
    }
}
