//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rak
    {
        public int id { get; set; }
        public string rak_name { get; set; }
        public string rak_desc { get; set; }
        public Nullable<int> shelf_id { get; set; }
    
        public virtual Shelf Shelf { get; set; }
    }
}
