//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_COUNTRY1
    {
        public int CN_ID { get; set; }
        public string CN_CD { get; set; }
        public string CN_NAME { get; set; }
        public Nullable<int> CN_CURR { get; set; }
        public string CN_COMPCD { get; set; }
    }
}
