//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_DT_HRPAYADJ
    {
        public int PAD_ID { get; set; }
        public Nullable<int> PA_ID { get; set; }
        public string PA_DOCNO { get; set; }
        public Nullable<int> EM_ID { get; set; }
        public string EM_NAME { get; set; }
        public Nullable<int> TT_ID { get; set; }
        public string TT_DESC { get; set; }
        public Nullable<decimal> PAD_QTY { get; set; }
        public Nullable<decimal> PAD_RATE { get; set; }
        public Nullable<decimal> PAD_AMT { get; set; }
        public string PAD_REMARKS { get; set; }
    }
}
