//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HD_HRPAYADJ
    {
        public int PA_ID { get; set; }
        public string PA_HEADER { get; set; }
        public string PA_TITLE { get; set; }
        public string PA_MONTH { get; set; }
        public string PA_YEAR { get; set; }
        public Nullable<System.DateTime> PA_DOCDATE { get; set; }
        public string PA_DOCNO { get; set; }
    }
}
